"""initial_schema

Revision ID: 3bf566cddb7d
Revises: 
Create Date: 2026-09-10 23:49:14.778495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf566cddb7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rec_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_db', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rec_plans_id'), 'rec_plans', ['id'], unique=False)
    op.create_index(op.f('ix_rec_plans_name_db'), 'rec_plans', ['name_db'], unique=True)
    op.create_table('sys_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_coupons_code'), 'sys_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_sys_coupons_id'), 'sys_coupons', ['id'], unique=False)
    op.create_table('sys_image_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_phrase', sa.Text(), nullable=True),
    sa.Column('supported_ratios', sa.JSON(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_image_templates_id'), 'sys_image_templates', ['id'], unique=False)
    op.create_table('sys_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_modules_id'), 'sys_modules', ['id'], unique=False)
    op.create_index(op.f('ix_sys_modules_key'), 'sys_modules', ['key'], unique=True)
    op.create_table('sys_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_roles_id'), 'sys_roles', ['id'], unique=False)
    op.create_index(op.f('ix_sys_roles_key'), 'sys_roles', ['key'], unique=True)
    op.create_table('sys_saas_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('eslogan', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('mision', sa.String(), nullable=True),
    sa.Column('vision', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('redes_sociales', sa.JSON(), nullable=True),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('backup_enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_day', sa.Integer(), nullable=True),
    sa.Column('backup_time', sa.String(), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backup_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_sys_saas_config_id'), 'sys_saas_config', ['id'], unique=False)
    op.create_table('sys_subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('max_pets', sa.Integer(), nullable=True),
    sa.Column('max_services', sa.Integer(), nullable=True),
    sa.Column('max_plans', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_orders', sa.Integer(), nullable=True),
    sa.Column('max_customers', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_partners', sa.Integer(), nullable=True),
    sa.Column('allowed_modules', sa.JSON(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('annual_price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('polar_product_id', sa.String(), nullable=True),
    sa.Column('polar_price_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_subscription_plans_id'), 'sys_subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_sys_subscription_plans_name'), 'sys_subscription_plans', ['name'], unique=True)
    op.create_table('sys_veterinaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bank_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('polar_customer_id', sa.String(), nullable=True),
    sa.Column('polar_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('polar_cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_veterinaries_email'), 'sys_veterinaries', ['email'], unique=True)
    op.create_index(op.f('ix_sys_veterinaries_id'), 'sys_veterinaries', ['id'], unique=False)
    op.create_index(op.f('ix_sys_veterinaries_rut'), 'sys_veterinaries', ['rut'], unique=True)
    op.create_index(op.f('ix_sys_veterinaries_slug'), 'sys_veterinaries', ['slug'], unique=True)
    op.create_table('web_landing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_landing_configs_id'), 'web_landing_configs', ['id'], unique=False)
    op.create_index(op.f('ix_web_landing_configs_key'), 'web_landing_configs', ['key'], unique=True)
    op.create_table('web_media_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_media_categories_id'), 'web_media_categories', ['id'], unique=False)
    op.create_index(op.f('ix_web_media_categories_key'), 'web_media_categories', ['key'], unique=True)
    op.create_table('auth_role_module_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'recepcion', 'operador_cremacion', 'contabilidad', 'marketing', 'auditor', 'operator', 'driver', 'creator', name='userrole', native_enum=False), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['module_key'], ['sys_modules.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_role_module_blueprints_id'), 'auth_role_module_blueprints', ['id'], unique=False)
    op.create_table('sys_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('pending_reason', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('legal_rep_name', sa.String(), nullable=True),
    sa.Column('legal_rep_rut', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'pending', 'inactive', name='tenantstatus', native_enum=False), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('demo_plan_id', sa.Integer(), nullable=True),
    sa.Column('demo_expires_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('public_token', sa.String(), nullable=True),
    sa.Column('default_certificate_template_id', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('billing_status', sa.String(), nullable=True),
    sa.Column('billing_end_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_method', sa.String(), nullable=True),
    sa.Column('billing_notify_days', sa.Integer(), nullable=True),
    sa.Column('billing_notify_channels', sa.String(), nullable=True),
    sa.Column('billing_discount', sa.Integer(), nullable=True),
    sa.Column('polar_customer_id', sa.String(), nullable=True),
    sa.Column('polar_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('polar_cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['demo_plan_id'], ['sys_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['sys_subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenants_id'), 'sys_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenants_public_token'), 'sys_tenants', ['public_token'], unique=True)
    op.create_index(op.f('ix_sys_tenants_rut'), 'sys_tenants', ['rut'], unique=True)
    op.create_index(op.f('ix_sys_tenants_slug'), 'sys_tenants', ['slug'], unique=True)
    op.create_table('auth_tenant_module_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'recepcion', 'operador_cremacion', 'contabilidad', 'marketing', 'auditor', 'operator', 'driver', 'creator', name='userrole', native_enum=False), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_key'], ['sys_modules.key'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tenant_module_configs_id'), 'auth_tenant_module_configs', ['id'], unique=False)
    op.create_index(op.f('ix_auth_tenant_module_configs_tenant_id'), 'auth_tenant_module_configs', ['tenant_id'], unique=False)
    op.create_table('crm_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rut', name='uix_customer_rut_tenant')
    )
    op.create_index(op.f('ix_crm_customers_id'), 'crm_customers', ['id'], unique=False)
    op.create_index(op.f('ix_crm_customers_rut'), 'crm_customers', ['rut'], unique=False)
    op.create_index(op.f('ix_crm_customers_tenant_id'), 'crm_customers', ['tenant_id'], unique=False)
    op.create_table('inv_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uix_category_name_tenant')
    )
    op.create_index(op.f('ix_inv_categories_id'), 'inv_categories', ['id'], unique=False)
    op.create_index(op.f('ix_inv_categories_tenant_id'), 'inv_categories', ['tenant_id'], unique=False)
    op.create_table('inv_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rut', name='uix_provider_rut_tenant')
    )
    op.create_index(op.f('ix_inv_providers_id'), 'inv_providers', ['id'], unique=False)
    op.create_index(op.f('ix_inv_providers_tenant_id'), 'inv_providers', ['tenant_id'], unique=False)
    op.create_table('ops_certificate_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source_template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('paper_format', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('declaration_text', sa.String(), nullable=True),
    sa.Column('signature_text', sa.String(), nullable=True),
    sa.Column('memorial_message', sa.String(), nullable=True),
    sa.Column('memorial_title', sa.String(), nullable=True),
    sa.Column('header_logo_url', sa.String(), nullable=True),
    sa.Column('header_logo_x', sa.String(), nullable=True),
    sa.Column('header_logo_y', sa.String(), nullable=True),
    sa.Column('background_logo_url', sa.String(), nullable=True),
    sa.Column('background_logo_x', sa.String(), nullable=True),
    sa.Column('background_logo_y', sa.String(), nullable=True),
    sa.Column('background_logo_opacity', sa.Float(), nullable=True),
    sa.Column('background_logo_rotation', sa.Float(), nullable=True),
    sa.Column('header_logo_shape', sa.String(), nullable=True),
    sa.Column('background_logo_shape', sa.String(), nullable=True),
    sa.Column('farewell_text', sa.String(), nullable=True),
    sa.Column('sections_config', sa.JSON(), nullable=True),
    sa.Column('sections_order', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_template_id'], ['ops_certificate_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_certificate_templates_id'), 'ops_certificate_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ops_certificate_templates_source_template_id'), 'ops_certificate_templates', ['source_template_id'], unique=False)
    op.create_index(op.f('ix_ops_certificate_templates_tenant_id'), 'ops_certificate_templates', ['tenant_id'], unique=False)
    op.create_table('ops_farewell_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_farewell_templates_id'), 'ops_farewell_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ops_farewell_templates_tenant_id'), 'ops_farewell_templates', ['tenant_id'], unique=False)
    op.create_table('ops_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_workflow_steps_id'), 'ops_workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_ops_workflow_steps_tenant_id'), 'ops_workflow_steps', ['tenant_id'], unique=False)
    op.create_table('ptn_partner_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('veterinary_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='partnerlinkstatus', native_enum=False), nullable=True),
    sa.Column('slug_publico', sa.String(), nullable=False),
    sa.Column('tipo_comision', sa.String(), nullable=True),
    sa.Column('monto_comision', sa.Float(), nullable=True),
    sa.Column('porcentaje_comision', sa.Float(), nullable=True),
    sa.Column('bank_data_override', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['veterinary_id'], ['sys_veterinaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug_publico', name='uix_tenant_link_slug'),
    sa.UniqueConstraint('tenant_id', 'veterinary_id', name='uix_tenant_veterinary_link')
    )
    op.create_index(op.f('ix_ptn_partner_links_id'), 'ptn_partner_links', ['id'], unique=False)
    op.create_index(op.f('ix_ptn_partner_links_tenant_id'), 'ptn_partner_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ptn_partner_links_veterinary_id'), 'ptn_partner_links', ['veterinary_id'], unique=False)
    op.create_table('srv_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uix_plan_name_tenant')
    )
    op.create_index(op.f('ix_srv_plans_id'), 'srv_plans', ['id'], unique=False)
    op.create_index(op.f('ix_srv_plans_tenant_id'), 'srv_plans', ['tenant_id'], unique=False)
    op.create_table('srv_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uix_service_name_tenant')
    )
    op.create_index(op.f('ix_srv_services_id'), 'srv_services', ['id'], unique=False)
    op.create_index(op.f('ix_srv_services_tenant_id'), 'srv_services', ['tenant_id'], unique=False)
    op.create_table('srv_weight_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_weight_pricing_id'), 'srv_weight_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_srv_weight_pricing_tenant_id'), 'srv_weight_pricing', ['tenant_id'], unique=False)
    op.create_table('sys_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('veterinary_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.Enum('admin', 'tenant', 'veterinary', name='recipienttype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='notificationpriority', native_enum=False), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['veterinary_id'], ['sys_veterinaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_notifications_id'), 'sys_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_sys_notifications_is_read'), 'sys_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_sys_notifications_priority'), 'sys_notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_sys_notifications_recipient_type'), 'sys_notifications', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_sys_notifications_tenant_id'), 'sys_notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_notifications_veterinary_id'), 'sys_notifications', ['veterinary_id'], unique=False)
    op.create_table('sys_table_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('columns_config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_table_configurations_id'), 'sys_table_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_sys_table_configurations_tenant_id'), 'sys_table_configurations', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('info', 'promo', 'alert', 'welcome', 'update', name='announcementtype', native_enum=False), nullable=False),
    sa.Column('display_type', sa.Enum('modal', 'banner', name='announcementdisplaytype', native_enum=False), nullable=True),
    sa.Column('target_status', sa.Enum('active', 'suspended', 'pending', 'inactive', name='tenantstatus', native_enum=False), nullable=True),
    sa.Column('target_plan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('show_once', sa.Boolean(), nullable=True),
    sa.Column('must_read', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_plan_id'], ['sys_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_announcements_id'), 'sys_tenant_announcements', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_announcements_tenant_id'), 'sys_tenant_announcements', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_api_keys_api_key'), 'sys_tenant_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_sys_tenant_api_keys_id'), 'sys_tenant_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_api_keys_tenant_id'), 'sys_tenant_api_keys', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_billing_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_billing_info_id'), 'sys_tenant_billing_info', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_billing_info_tenant_id'), 'sys_tenant_billing_info', ['tenant_id'], unique=True)
    op.create_table('sys_tenant_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'expired', 'canceled', 'trial', name='subscriptionstatus'), nullable=True),
    sa.Column('billing_cycle', sa.Enum('monthly', 'bimonthly', 'semiannual', 'annual', name='billingcycle'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['sys_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_subscriptions_id'), 'sys_tenant_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_subscriptions_status'), 'sys_tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_sys_tenant_subscriptions_tenant_id'), 'sys_tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'recepcion', 'operador_cremacion', 'contabilidad', 'marketing', 'auditor', 'operator', 'driver', 'creator', name='userrole', native_enum=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=True)
    op.create_index(op.f('ix_sys_users_id'), 'sys_users', ['id'], unique=False)
    op.create_table('web_media_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ratio', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('theme_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_media_library_id'), 'web_media_library', ['id'], unique=False)
    op.create_index(op.f('ix_web_media_library_tenant_id'), 'web_media_library', ['tenant_id'], unique=False)
    op.create_table('web_theme_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('theme_mode', sa.String(), nullable=True),
    sa.Column('auto_light_start', sa.String(), nullable=True),
    sa.Column('auto_light_end', sa.String(), nullable=True),
    sa.Column('custom_theme_colors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_theme_config_id'), 'web_theme_config', ['id'], unique=False)
    op.create_index(op.f('ix_web_theme_config_tenant_id'), 'web_theme_config', ['tenant_id'], unique=True)
    op.create_table('auth_user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_key'], ['sys_modules.key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_module_permissions_id'), 'auth_user_module_permissions', ['id'], unique=False)
    op.create_table('crm_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'delivered', name='petstatus', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', 'name', name='uix_pet_name_customer_tenant')
    )
    op.create_index(op.f('ix_crm_pets_id'), 'crm_pets', ['id'], unique=False)
    op.create_index(op.f('ix_crm_pets_tenant_id'), 'crm_pets', ['tenant_id'], unique=False)
    op.create_table('inv_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inv_categories.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['inv_providers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uix_product_code_tenant')
    )
    op.create_index(op.f('ix_inv_products_code'), 'inv_products', ['code'], unique=False)
    op.create_index(op.f('ix_inv_products_id'), 'inv_products', ['id'], unique=False)
    op.create_index(op.f('ix_inv_products_tenant_id'), 'inv_products', ['tenant_id'], unique=False)
    op.create_table('srv_plan_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['srv_plans.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['srv_services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_plan_services_id'), 'srv_plan_services', ['id'], unique=False)
    op.create_index(op.f('ix_srv_plan_services_tenant_id'), 'srv_plan_services', ['tenant_id'], unique=False)
    op.create_table('sys_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_audit_logs_created_at'), 'sys_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_audit_logs_id'), 'sys_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sys_audit_logs_tenant_id'), 'sys_audit_logs', ['tenant_id'], unique=False)
    op.create_table('sys_billing_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('transfer', 'stripe', 'paypal', 'cash', 'polar', 'mercadopago', name='paymentmethod'), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('target_plan_id', sa.Integer(), nullable=True),
    sa.Column('target_billing_cycle', sa.Enum('monthly', 'bimonthly', 'semiannual', 'annual', name='billingcycle'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['sys_tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['target_plan_id'], ['sys_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_billing_transactions_id'), 'sys_billing_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_billing_transactions_payment_date'), 'sys_billing_transactions', ['payment_date'], unique=False)
    op.create_index(op.f('ix_sys_billing_transactions_payment_status'), 'sys_billing_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_sys_billing_transactions_tenant_id'), 'sys_billing_transactions', ['tenant_id'], unique=False)
    op.create_table('sys_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['sys_refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_refresh_tokens_id'), 'sys_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_sys_refresh_tokens_token_hash'), 'sys_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sys_refresh_tokens_user_id'), 'sys_refresh_tokens', ['user_id'], unique=False)
    op.create_table('sys_temporary_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_temporary_tokens_expires_at'), 'sys_temporary_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sys_temporary_tokens_id'), 'sys_temporary_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_sys_temporary_tokens_tenant_id'), 'sys_temporary_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_temporary_tokens_token'), 'sys_temporary_tokens', ['token'], unique=True)
    op.create_table('sys_user_announcement_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['sys_tenant_announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_announcement_views_announcement_id'), 'sys_user_announcement_views', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_sys_user_announcement_views_id'), 'sys_user_announcement_views', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_announcement_views_user_id'), 'sys_user_announcement_views', ['user_id'], unique=False)
    op.create_table('oc_cremations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('oc_number', sa.Integer(), nullable=True),
    sa.Column('cremation_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('partner_link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_link_id'], ['ptn_partner_links.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['crm_pets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oc_cremations_id'), 'oc_cremations', ['id'], unique=False)
    op.create_index(op.f('ix_oc_cremations_partner_link_id'), 'oc_cremations', ['partner_link_id'], unique=False)
    op.create_index(op.f('ix_oc_cremations_tenant_id'), 'oc_cremations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_oc_cremations_verification_code'), 'oc_cremations', ['verification_code'], unique=True)
    op.create_table('rec_recuerdos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_recuerdo', sa.UUID(), nullable=True),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('diseno', sa.JSON(), nullable=True),
    sa.Column('lista_imagenes', sa.JSON(), nullable=True),
    sa.Column('main_image_url', sa.String(), nullable=True),
    sa.Column('imagen_ia', sa.String(), nullable=True),
    sa.Column('msg_despedida', sa.String(length=1050), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('access_key', sa.String(length=6), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'archived', 'expired', name='memorialstatus', native_enum=False), nullable=True),
    sa.Column('es_privado', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('polar_customer_id', sa.String(), nullable=True),
    sa.Column('polar_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('polar_cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['crm_pets.id'], ),
    sa.ForeignKeyConstraint(['id_tenant'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['rec_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rec_recuerdos_id'), 'rec_recuerdos', ['id'], unique=False)
    op.create_index(op.f('ix_rec_recuerdos_id_recuerdo'), 'rec_recuerdos', ['id_recuerdo'], unique=True)
    op.create_index(op.f('ix_rec_recuerdos_id_tenant'), 'rec_recuerdos', ['id_tenant'], unique=False)
    op.create_table('srv_plan_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['srv_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inv_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_plan_products_id'), 'srv_plan_products', ['id'], unique=False)
    op.create_index(op.f('ix_srv_plan_products_tenant_id'), 'srv_plan_products', ['tenant_id'], unique=False)
    op.create_table('sys_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_email', sa.String(length=255), nullable=True),
    sa.Column('tenant_phone', sa.String(length=50), nullable=True),
    sa.Column('tenant_address', sa.Text(), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('issuer_rut', sa.String(length=50), nullable=True),
    sa.Column('issuer_address', sa.Text(), nullable=True),
    sa.Column('issuer_email', sa.String(length=255), nullable=True),
    sa.Column('issuer_logo_url', sa.Text(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'voided', 'replaced', name='receiptstatus'), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('replaced_by_receipt_id', sa.Integer(), nullable=True),
    sa.Column('replaces_receipt_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ops_certificate_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['sys_billing_transactions.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_receipts_id'), 'sys_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_sys_receipts_issued_at'), 'sys_receipts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_sys_receipts_receipt_number'), 'sys_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_sys_receipts_status'), 'sys_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_sys_receipts_tenant_id'), 'sys_receipts', ['tenant_id'], unique=False)
    op.create_table('web_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('owner_data', sa.JSON(), nullable=False),
    sa.Column('pet_data', sa.JSON(), nullable=False),
    sa.Column('selected_services', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['crm_pets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_form_submissions_code'), 'web_form_submissions', ['code'], unique=True)
    op.create_index(op.f('ix_web_form_submissions_id'), 'web_form_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_web_form_submissions_slug'), 'web_form_submissions', ['slug'], unique=False)
    op.create_index(op.f('ix_web_form_submissions_tenant_id'), 'web_form_submissions', ['tenant_id'], unique=False)
    op.create_table('oc_cremation_technical',
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('furnace_id', sa.String(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['ops_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('cremation_id')
    )
    op.create_table('oc_details',
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('service_code', sa.String(), nullable=True),
    sa.Column('tracking_token', sa.String(), nullable=True),
    sa.Column('additional_services', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('cremation_id')
    )
    op.create_index(op.f('ix_oc_details_tenant_id'), 'oc_details', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_oc_details_tracking_token'), 'oc_details', ['tracking_token'], unique=True)
    op.create_table('oc_financial',
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('weight_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('cremation_id')
    )
    op.create_index(op.f('ix_oc_financial_tenant_id'), 'oc_financial', ['tenant_id'], unique=False)
    op.create_table('oc_logistics',
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pickup_region', sa.String(), nullable=True),
    sa.Column('pickup_city', sa.String(), nullable=True),
    sa.Column('pickup_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('cremation_id')
    )
    op.create_index(op.f('ix_oc_logistics_tenant_id'), 'oc_logistics', ['tenant_id'], unique=False)
    op.create_table('oc_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_costo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['srv_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oc_plans_id'), 'oc_plans', ['id'], unique=False)
    op.create_index(op.f('ix_oc_plans_tenant_id'), 'oc_plans', ['tenant_id'], unique=False)
    op.create_table('oc_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_costo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inv_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oc_products_id'), 'oc_products', ['id'], unique=False)
    op.create_index(op.f('ix_oc_products_tenant_id'), 'oc_products', ['tenant_id'], unique=False)
    op.create_table('oc_scheduling',
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('cremation_id')
    )
    op.create_index(op.f('ix_oc_scheduling_tenant_id'), 'oc_scheduling', ['tenant_id'], unique=False)
    op.create_table('oc_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_costo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['srv_services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oc_services_id'), 'oc_services', ['id'], unique=False)
    op.create_index(op.f('ix_oc_services_tenant_id'), 'oc_services', ['tenant_id'], unique=False)
    op.create_table('ops_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('html_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_ops_certificates_id'), 'ops_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_ops_certificates_tenant_id'), 'ops_certificates', ['tenant_id'], unique=False)
    op.create_table('ops_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_documents_id'), 'ops_documents', ['id'], unique=False)
    op.create_index(op.f('ix_ops_documents_tenant_id'), 'ops_documents', ['tenant_id'], unique=False)
    op.create_table('ops_logistics_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('cremation_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('evidence_image_url', sa.String(), nullable=True),
    sa.Column('signature_url', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_logistics_tasks_id'), 'ops_logistics_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_ops_logistics_tasks_tenant_id'), 'ops_logistics_tasks', ['tenant_id'], unique=False)
    op.create_table('ops_order_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['ops_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_order_evidence_cremation_id'), 'ops_order_evidence', ['cremation_id'], unique=False)
    op.create_index(op.f('ix_ops_order_evidence_id'), 'ops_order_evidence', ['id'], unique=False)
    op.create_table('ptn_partner_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cremation_id', sa.Integer(), nullable=False),
    sa.Column('partner_link_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_porcentaje', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'pagado', 'cancelado', name='partnercommissionstatus', native_enum=False), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cremation_id'], ['oc_cremations.id'], ),
    sa.ForeignKeyConstraint(['partner_link_id'], ['ptn_partner_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ptn_partner_commissions_cremation_id'), 'ptn_partner_commissions', ['cremation_id'], unique=False)
    op.create_index(op.f('ix_ptn_partner_commissions_id'), 'ptn_partner_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_ptn_partner_commissions_partner_link_id'), 'ptn_partner_commissions', ['partner_link_id'], unique=False)
    op.create_table('rec_dedicatoria',
    sa.Column('id_dedicatoria', sa.Integer(), nullable=False),
    sa.Column('id_recuerdo', sa.Integer(), nullable=False),
    sa.Column('mensajero', sa.String(length=100), nullable=True),
    sa.Column('mensaje', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='dedicationstatus', native_enum=False), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_recuerdo'], ['rec_recuerdos.id'], ),
    sa.PrimaryKeyConstraint('id_dedicatoria')
    )
    op.create_index(op.f('ix_rec_dedicatoria_id_dedicatoria'), 'rec_dedicatoria', ['id_dedicatoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rec_dedicatoria_id_dedicatoria'), table_name='rec_dedicatoria')
    op.drop_table('rec_dedicatoria')
    op.drop_index(op.f('ix_ptn_partner_commissions_partner_link_id'), table_name='ptn_partner_commissions')
    op.drop_index(op.f('ix_ptn_partner_commissions_id'), table_name='ptn_partner_commissions')
    op.drop_index(op.f('ix_ptn_partner_commissions_cremation_id'), table_name='ptn_partner_commissions')
    op.drop_table('ptn_partner_commissions')
    op.drop_index(op.f('ix_ops_order_evidence_id'), table_name='ops_order_evidence')
    op.drop_index(op.f('ix_ops_order_evidence_cremation_id'), table_name='ops_order_evidence')
    op.drop_table('ops_order_evidence')
    op.drop_index(op.f('ix_ops_logistics_tasks_tenant_id'), table_name='ops_logistics_tasks')
    op.drop_index(op.f('ix_ops_logistics_tasks_id'), table_name='ops_logistics_tasks')
    op.drop_table('ops_logistics_tasks')
    op.drop_index(op.f('ix_ops_documents_tenant_id'), table_name='ops_documents')
    op.drop_index(op.f('ix_ops_documents_id'), table_name='ops_documents')
    op.drop_table('ops_documents')
    op.drop_index(op.f('ix_ops_certificates_tenant_id'), table_name='ops_certificates')
    op.drop_index(op.f('ix_ops_certificates_id'), table_name='ops_certificates')
    op.drop_table('ops_certificates')
    op.drop_index(op.f('ix_oc_services_tenant_id'), table_name='oc_services')
    op.drop_index(op.f('ix_oc_services_id'), table_name='oc_services')
    op.drop_table('oc_services')
    op.drop_index(op.f('ix_oc_scheduling_tenant_id'), table_name='oc_scheduling')
    op.drop_table('oc_scheduling')
    op.drop_index(op.f('ix_oc_products_tenant_id'), table_name='oc_products')
    op.drop_index(op.f('ix_oc_products_id'), table_name='oc_products')
    op.drop_table('oc_products')
    op.drop_index(op.f('ix_oc_plans_tenant_id'), table_name='oc_plans')
    op.drop_index(op.f('ix_oc_plans_id'), table_name='oc_plans')
    op.drop_table('oc_plans')
    op.drop_index(op.f('ix_oc_logistics_tenant_id'), table_name='oc_logistics')
    op.drop_table('oc_logistics')
    op.drop_index(op.f('ix_oc_financial_tenant_id'), table_name='oc_financial')
    op.drop_table('oc_financial')
    op.drop_index(op.f('ix_oc_details_tracking_token'), table_name='oc_details')
    op.drop_index(op.f('ix_oc_details_tenant_id'), table_name='oc_details')
    op.drop_table('oc_details')
    op.drop_table('oc_cremation_technical')
    op.drop_index(op.f('ix_web_form_submissions_tenant_id'), table_name='web_form_submissions')
    op.drop_index(op.f('ix_web_form_submissions_slug'), table_name='web_form_submissions')
    op.drop_index(op.f('ix_web_form_submissions_id'), table_name='web_form_submissions')
    op.drop_index(op.f('ix_web_form_submissions_code'), table_name='web_form_submissions')
    op.drop_table('web_form_submissions')
    op.drop_index(op.f('ix_sys_receipts_tenant_id'), table_name='sys_receipts')
    op.drop_index(op.f('ix_sys_receipts_status'), table_name='sys_receipts')
    op.drop_index(op.f('ix_sys_receipts_receipt_number'), table_name='sys_receipts')
    op.drop_index(op.f('ix_sys_receipts_issued_at'), table_name='sys_receipts')
    op.drop_index(op.f('ix_sys_receipts_id'), table_name='sys_receipts')
    op.drop_table('sys_receipts')
    op.drop_index(op.f('ix_srv_plan_products_tenant_id'), table_name='srv_plan_products')
    op.drop_index(op.f('ix_srv_plan_products_id'), table_name='srv_plan_products')
    op.drop_table('srv_plan_products')
    op.drop_index(op.f('ix_rec_recuerdos_id_tenant'), table_name='rec_recuerdos')
    op.drop_index(op.f('ix_rec_recuerdos_id_recuerdo'), table_name='rec_recuerdos')
    op.drop_index(op.f('ix_rec_recuerdos_id'), table_name='rec_recuerdos')
    op.drop_table('rec_recuerdos')
    op.drop_index(op.f('ix_oc_cremations_verification_code'), table_name='oc_cremations')
    op.drop_index(op.f('ix_oc_cremations_tenant_id'), table_name='oc_cremations')
    op.drop_index(op.f('ix_oc_cremations_partner_link_id'), table_name='oc_cremations')
    op.drop_index(op.f('ix_oc_cremations_id'), table_name='oc_cremations')
    op.drop_table('oc_cremations')
    op.drop_index(op.f('ix_sys_user_announcement_views_user_id'), table_name='sys_user_announcement_views')
    op.drop_index(op.f('ix_sys_user_announcement_views_id'), table_name='sys_user_announcement_views')
    op.drop_index(op.f('ix_sys_user_announcement_views_announcement_id'), table_name='sys_user_announcement_views')
    op.drop_table('sys_user_announcement_views')
    op.drop_index(op.f('ix_sys_temporary_tokens_token'), table_name='sys_temporary_tokens')
    op.drop_index(op.f('ix_sys_temporary_tokens_tenant_id'), table_name='sys_temporary_tokens')
    op.drop_index(op.f('ix_sys_temporary_tokens_id'), table_name='sys_temporary_tokens')
    op.drop_index(op.f('ix_sys_temporary_tokens_expires_at'), table_name='sys_temporary_tokens')
    op.drop_table('sys_temporary_tokens')
    op.drop_index(op.f('ix_sys_refresh_tokens_user_id'), table_name='sys_refresh_tokens')
    op.drop_index(op.f('ix_sys_refresh_tokens_token_hash'), table_name='sys_refresh_tokens')
    op.drop_index(op.f('ix_sys_refresh_tokens_id'), table_name='sys_refresh_tokens')
    op.drop_table('sys_refresh_tokens')
    op.drop_index(op.f('ix_sys_billing_transactions_tenant_id'), table_name='sys_billing_transactions')
    op.drop_index(op.f('ix_sys_billing_transactions_payment_status'), table_name='sys_billing_transactions')
    op.drop_index(op.f('ix_sys_billing_transactions_payment_date'), table_name='sys_billing_transactions')
    op.drop_index(op.f('ix_sys_billing_transactions_id'), table_name='sys_billing_transactions')
    op.drop_table('sys_billing_transactions')
    op.drop_index(op.f('ix_sys_audit_logs_tenant_id'), table_name='sys_audit_logs')
    op.drop_index(op.f('ix_sys_audit_logs_id'), table_name='sys_audit_logs')
    op.drop_index(op.f('ix_sys_audit_logs_created_at'), table_name='sys_audit_logs')
    op.drop_table('sys_audit_logs')
    op.drop_index(op.f('ix_srv_plan_services_tenant_id'), table_name='srv_plan_services')
    op.drop_index(op.f('ix_srv_plan_services_id'), table_name='srv_plan_services')
    op.drop_table('srv_plan_services')
    op.drop_index(op.f('ix_inv_products_tenant_id'), table_name='inv_products')
    op.drop_index(op.f('ix_inv_products_id'), table_name='inv_products')
    op.drop_index(op.f('ix_inv_products_code'), table_name='inv_products')
    op.drop_table('inv_products')
    op.drop_index(op.f('ix_crm_pets_tenant_id'), table_name='crm_pets')
    op.drop_index(op.f('ix_crm_pets_id'), table_name='crm_pets')
    op.drop_table('crm_pets')
    op.drop_index(op.f('ix_auth_user_module_permissions_id'), table_name='auth_user_module_permissions')
    op.drop_table('auth_user_module_permissions')
    op.drop_index(op.f('ix_web_theme_config_tenant_id'), table_name='web_theme_config')
    op.drop_index(op.f('ix_web_theme_config_id'), table_name='web_theme_config')
    op.drop_table('web_theme_config')
    op.drop_index(op.f('ix_web_media_library_tenant_id'), table_name='web_media_library')
    op.drop_index(op.f('ix_web_media_library_id'), table_name='web_media_library')
    op.drop_table('web_media_library')
    op.drop_index(op.f('ix_sys_users_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_tenant_subscriptions_tenant_id'), table_name='sys_tenant_subscriptions')
    op.drop_index(op.f('ix_sys_tenant_subscriptions_status'), table_name='sys_tenant_subscriptions')
    op.drop_index(op.f('ix_sys_tenant_subscriptions_id'), table_name='sys_tenant_subscriptions')
    op.drop_table('sys_tenant_subscriptions')
    op.drop_index(op.f('ix_sys_tenant_billing_info_tenant_id'), table_name='sys_tenant_billing_info')
    op.drop_index(op.f('ix_sys_tenant_billing_info_id'), table_name='sys_tenant_billing_info')
    op.drop_table('sys_tenant_billing_info')
    op.drop_index(op.f('ix_sys_tenant_api_keys_tenant_id'), table_name='sys_tenant_api_keys')
    op.drop_index(op.f('ix_sys_tenant_api_keys_id'), table_name='sys_tenant_api_keys')
    op.drop_index(op.f('ix_sys_tenant_api_keys_api_key'), table_name='sys_tenant_api_keys')
    op.drop_table('sys_tenant_api_keys')
    op.drop_index(op.f('ix_sys_tenant_announcements_tenant_id'), table_name='sys_tenant_announcements')
    op.drop_index(op.f('ix_sys_tenant_announcements_id'), table_name='sys_tenant_announcements')
    op.drop_table('sys_tenant_announcements')
    op.drop_index(op.f('ix_sys_table_configurations_tenant_id'), table_name='sys_table_configurations')
    op.drop_index(op.f('ix_sys_table_configurations_id'), table_name='sys_table_configurations')
    op.drop_table('sys_table_configurations')
    op.drop_index(op.f('ix_sys_notifications_veterinary_id'), table_name='sys_notifications')
    op.drop_index(op.f('ix_sys_notifications_tenant_id'), table_name='sys_notifications')
    op.drop_index(op.f('ix_sys_notifications_recipient_type'), table_name='sys_notifications')
    op.drop_index(op.f('ix_sys_notifications_priority'), table_name='sys_notifications')
    op.drop_index(op.f('ix_sys_notifications_is_read'), table_name='sys_notifications')
    op.drop_index(op.f('ix_sys_notifications_id'), table_name='sys_notifications')
    op.drop_table('sys_notifications')
    op.drop_index(op.f('ix_srv_weight_pricing_tenant_id'), table_name='srv_weight_pricing')
    op.drop_index(op.f('ix_srv_weight_pricing_id'), table_name='srv_weight_pricing')
    op.drop_table('srv_weight_pricing')
    op.drop_index(op.f('ix_srv_services_tenant_id'), table_name='srv_services')
    op.drop_index(op.f('ix_srv_services_id'), table_name='srv_services')
    op.drop_table('srv_services')
    op.drop_index(op.f('ix_srv_plans_tenant_id'), table_name='srv_plans')
    op.drop_index(op.f('ix_srv_plans_id'), table_name='srv_plans')
    op.drop_table('srv_plans')
    op.drop_index(op.f('ix_ptn_partner_links_veterinary_id'), table_name='ptn_partner_links')
    op.drop_index(op.f('ix_ptn_partner_links_tenant_id'), table_name='ptn_partner_links')
    op.drop_index(op.f('ix_ptn_partner_links_id'), table_name='ptn_partner_links')
    op.drop_table('ptn_partner_links')
    op.drop_index(op.f('ix_ops_workflow_steps_tenant_id'), table_name='ops_workflow_steps')
    op.drop_index(op.f('ix_ops_workflow_steps_id'), table_name='ops_workflow_steps')
    op.drop_table('ops_workflow_steps')
    op.drop_index(op.f('ix_ops_farewell_templates_tenant_id'), table_name='ops_farewell_templates')
    op.drop_index(op.f('ix_ops_farewell_templates_id'), table_name='ops_farewell_templates')
    op.drop_table('ops_farewell_templates')
    op.drop_index(op.f('ix_ops_certificate_templates_tenant_id'), table_name='ops_certificate_templates')
    op.drop_index(op.f('ix_ops_certificate_templates_source_template_id'), table_name='ops_certificate_templates')
    op.drop_index(op.f('ix_ops_certificate_templates_id'), table_name='ops_certificate_templates')
    op.drop_table('ops_certificate_templates')
    op.drop_index(op.f('ix_inv_providers_tenant_id'), table_name='inv_providers')
    op.drop_index(op.f('ix_inv_providers_id'), table_name='inv_providers')
    op.drop_table('inv_providers')
    op.drop_index(op.f('ix_inv_categories_tenant_id'), table_name='inv_categories')
    op.drop_index(op.f('ix_inv_categories_id'), table_name='inv_categories')
    op.drop_table('inv_categories')
    op.drop_index(op.f('ix_crm_customers_tenant_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_rut'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_id'), table_name='crm_customers')
    op.drop_table('crm_customers')
    op.drop_index(op.f('ix_auth_tenant_module_configs_tenant_id'), table_name='auth_tenant_module_configs')
    op.drop_index(op.f('ix_auth_tenant_module_configs_id'), table_name='auth_tenant_module_configs')
    op.drop_table('auth_tenant_module_configs')
    op.drop_index(op.f('ix_sys_tenants_slug'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_rut'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_public_token'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_id'), table_name='sys_tenants')
    op.drop_table('sys_tenants')
    op.drop_index(op.f('ix_auth_role_module_blueprints_id'), table_name='auth_role_module_blueprints')
    op.drop_table('auth_role_module_blueprints')
    op.drop_index(op.f('ix_web_media_categories_key'), table_name='web_media_categories')
    op.drop_index(op.f('ix_web_media_categories_id'), table_name='web_media_categories')
    op.drop_table('web_media_categories')
    op.drop_index(op.f('ix_web_landing_configs_key'), table_name='web_landing_configs')
    op.drop_index(op.f('ix_web_landing_configs_id'), table_name='web_landing_configs')
    op.drop_table('web_landing_configs')
    op.drop_index(op.f('ix_sys_veterinaries_slug'), table_name='sys_veterinaries')
    op.drop_index(op.f('ix_sys_veterinaries_rut'), table_name='sys_veterinaries')
    op.drop_index(op.f('ix_sys_veterinaries_id'), table_name='sys_veterinaries')
    op.drop_index(op.f('ix_sys_veterinaries_email'), table_name='sys_veterinaries')
    op.drop_table('sys_veterinaries')
    op.drop_index(op.f('ix_sys_subscription_plans_name'), table_name='sys_subscription_plans')
    op.drop_index(op.f('ix_sys_subscription_plans_id'), table_name='sys_subscription_plans')
    op.drop_table('sys_subscription_plans')
    op.drop_index(op.f('ix_sys_saas_config_id'), table_name='sys_saas_config')
    op.drop_table('sys_saas_config')
    op.drop_index(op.f('ix_sys_roles_key'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_id'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_sys_modules_key'), table_name='sys_modules')
    op.drop_index(op.f('ix_sys_modules_id'), table_name='sys_modules')
    op.drop_table('sys_modules')
    op.drop_index(op.f('ix_sys_image_templates_id'), table_name='sys_image_templates')
    op.drop_table('sys_image_templates')
    op.drop_index(op.f('ix_sys_coupons_id'), table_name='sys_coupons')
    op.drop_index(op.f('ix_sys_coupons_code'), table_name='sys_coupons')
    op.drop_table('sys_coupons')
    op.drop_index(op.f('ix_rec_plans_name_db'), table_name='rec_plans')
    op.drop_index(op.f('ix_rec_plans_id'), table_name='rec_plans')
    op.drop_table('rec_plans')
    # ### end Alembic commands ###
